export const projects = [
{
    title: 'YourFitnessFriend',
    description: "This was my very first web application! Created during phase 1 of my bootcamp using vanilla JS and CSS. I thought about refactoring this and fully updating it, but I like being able to look back and see where I started.",
    image: 'https://i.imgur.com/r80auoK.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/Jrobbins973/Exercise-api',
    video: 'https://www.youtube.com/watch?v=N-IjnXJAWWA',
    technology: 'JavaScript, HTML/CSS',
    id: 0,
},
{
    title: 'Pro-active',
    description:"This was my first group project and therefore my first entry into version control with Github, which was an interesting experience to say the least. But hey, having merge conflicts and having to re-do large portions of your code base is all apart of the journey, right?... Also, this was our first time using a styling library (SemanticUI), which at the time I was a HUGE fan of, but have since moved on from it due to it's lack of easy customization compared to CSS.",
    image: 'https://i.imgur.com/hy1sasZ.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/Jrobbins973/Phase-2-Project',
    video: 'https://www.youtube.com/watch?v=xLumepkzLEM',
    technology: "React, SemanticUI, CSS",
    id: 1,
},
{
    title: 'MovieBuddy',
    description: "This project was a great lesson in the fact that programming languages are very much a 'Use it or Lose It' skill. For this phase of the bootcamp we were learning Ruby to start developing a custom RESTful API. While that was going swimmingly, by the time project week came around I hadn't touched React in about 3 weeks. So when it came time to make the front-end of my project, I spent an embarrassing amount of time trying to remember how inverse data flow worked and why stuff wasn't showing up on my page.. so, note to self: don't completely abandon an old language when the new shiny language comes along, it might come back to bite you.",
    image: 'https://i.imgur.com/4ttIp9o.jpg',
    tags: ['React', 'WebRTC'],
    source: 'https://github.com/Jrobbins973/phase-3-front-end-react',
    video: '',
    technology: 'React, Sinatra/Active Record, CSS, SemanticUI',
    id: 2,
},
{
    title: 'Reactr',
    description: "During phase 4 of my bootcamp we learned Ruby on Rails, and with that, user authentication and authorization. This broadened the horizon for projects a bit. For this project my partner and I set out to make a twitter 'clone'. We were able to get the core functionality of it down, with significantly less conspiracy theories than regular twitter, so I consider that a win.",
    image: 'https://i.imgur.com/RAuy4FJ.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/nardling/phase-4-project',
    video: '',
    technology: 'React, Ruby on Rails, CSS',
    id: 3,
},
{
    title: 'ApartmentConnect',
    description: "This was my capstone project, and it was a fun one. For all other projects we had about 3-4 days to create them, but for this capstone, we had 4 weeks to do it thanks to winter break adding an extra week. This allowed for significantly more styling time, and time to add those small touches that make a site pleasant to use. Developing a project this big was a great confidence boost that the time and effort put into this bootcamp was worth it, and also gave me great appreciation for the well designed user experience that some websites offer; and some questions about websites that questionably lack the fit and finish that is expected in 2023 (looking at you craigslist...).",
    image: 'https://i.imgur.com/K6EavPu.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/Jrobbins973/ApartmentConnect-FrontEnd',
    video: '',
    technology: 'React, Ruby on Rails, PostgreSQL, CSS',
    id: 4,
}
];